### PR TITLE
Update plots per issue 4

### PR DESCRIPTION
**Pull request by rpitingolo**
@alenastern updated HTML output ready for review. I was successfully able to convert the ggpltos to library(plotly) and make them vertically shorter.

You asked for "Make X axes consistent across geographies" which I assume meant fixed min and max but that didn't really work because the Illinois numbers were a magnitude greater than the local numbers. But I just set the min and max for Illinois x10 and I think it accomplishes what you wanted to do. Let me know if I misunderstood that one. 

I have a placeholder for the explanatory language about why some numbers are greater than 100%. I'm not familiar enough with the topic to confidently explain it. If you can point me in the direction of the text that I can use that would be helpful. Thanks!

### CODE REVIEW

**Comment by rpitingolo** [comment]
@alenastern pushed edits for the tasks on issues 4, 5 and 6. Ready for you to review.

**Comment by alenastern** [comment]
Hi Rob! A couple of quick fixes:

For #5 - 

- [x] Remove the "Current Spending Compared to Original Allocations" title
- [x] for the tooltip,  change "Current Spending" to "Adopted budget"
- [x] looks like the "Percent of obligated funds spent" Illinois chart is still hanging on if you would please remove!

For #6 -

- [x] Change "Original Allocation" to "Adopted budget" in tool tip
- [x] Change x-axis scale to show 100% (perhaps 0, 20, 40, 60, 80, 100)

For both issues, it would be nice to eventually make the tool tip text for the dollar amounts look nicer with the currency formatting, but I'll add that as a separate issue for later! Thank you!

**Review by alenastern — CHANGES_REQUESTED** [review]
See comment for requested changes!

**Comment by rpitingolo** [comment]
@alenastern OK I think I've got all these changes in and I cleaned up the tooltip code to use currency formatting.

**Review by alenastern — APPROVED** [review]
Looks good! thanks @rpitingolo

**Pull request merged**
